---
- name: Service started {{ daemon_name }}
  service:
    name: "{{ daemon_name }}"
    state: started
    enabled: yes
  listen: Service started {{ daemon_name }}

- name: Service restarted {{ daemon_name }}
  service:
    name: "{{ daemon_name }}"
    state: restarted
  listen: Service restarted {{ daemon_name }}

- name: Service reloaded {{ daemon_name }}
  service:
    name: "{{ daemon_name }}"
    state: reloaded
  listen: Service reloaded {{ daemon_name }}

- name: Service stopped {{ daemon_name }}
  service:
    name: "{{ daemon_name }}"
    state: stopped
    enabled: no
  listen: Service stopped {{ daemon_name }}

- name: Systemd started {{ daemon_name }}
  systemd:
    name: "{{ daemon_name }}"
    state: started
    enabled: yes
  listen: Systemd started {{ daemon_name }}

- name: Systemd restarted {{ daemon_name }}
  systemd:
    name: "{{ daemon_name }}"
    state: restarted
  listen: Systemd restarted {{ daemon_name }}

- name: Systemd reloaded {{ daemon_name }}
  systemd:
    name: "{{ daemon_name }}"
    state: reloaded
  listen: Systemd reloaded {{ daemon_name }}

- name: Systemd stopped {{ daemon_name }}
  systemd:
    name: "{{ daemon_name }}"
    state: stopped
    enabled: no
  listen: Systemd stopped {{ daemon_name }}
