---
- name: Install Repo
  yum:
    name: "{{ URL_REPO }}{{ VERSION_ZABBIX_SERVER }}/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/zabbix-release-{{ VERSION_ZABBIX_SERVER }}-{{ VERSION_MINOR_ZABBIX_SERVER }}.el{{ ansible_distribution_major_version }}.noarch.rpm"
