---
- name: Install Repo
  yum:
    name: "{{ URL_REPO }}{{ VERSION_ZABBIX_SERVER }}/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/zabbix-release-{{ VERSION_ZABBIX_SERVER }}-{{ VERSION_MINOR_ZABBIX_SERVER }}.el{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Install Zabbix-Server
  yum:
    name: zabbix-server

- name: Daemon Started
  include_role:
    name: common_tasks
    tasks_from: service_started_{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml

- include_role:
    name: common_tasks
    tasks_from: flush_handlers.yml
