---
- name: Setup Config
  template:
    src: zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: Service restarted {{ daemon_name }}
