---
- name: Install Server
  yum:
    name: httpd

- name: Daemon Started
  include_role:
    name: common_tasks
    tasks_from: service_started_{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml

- name: set facts allow http on firewalld
  set_fact:
    service: "http"
  register: firewalld_values

- include_role:
    name: common_tasks
    tasks_from: firewalld.yml
  with_items:
    - "{{ firewalld_values.ansible_facts }}"

- name: set facts allow https on firewalld
  set_fact:
    service: "https"
  register: firewalld_values

- include_role:
    name: common_tasks
    tasks_from: firewalld.yml
  with_items:
    - "{{ firewalld_values.ansible_facts }}"
