---
- name: Check State "{{ daemon_name }}"
  command: "systemctl status {{ daemon_name }}"
  register: service_status
  changed_when: False
  failed_when: False
  tags:
    - skip-check
    - service_stop

- name: Stopped "{{ daemon_name }}"
  command: echo "Stopped {{ daemon_name }}"
  when: service_status.rc != 3
  notify: Systemd stopped {{ daemon_name }}
  tags:
    - skip-check
    - service_stop
