---
- name: Check State "{{ daemon_name }}"
  shell: service {{ daemon_name }} status
  register: service_status
  changed_when: False
  failed_when: False
  ignore_errors: True
  tags:
    - skip-check
    - service_start

- name: Started "{{ daemon_name }}"
  shell: echo "Started {{ daemon_name }}"
  when: service_status.rc != 0
  notify: Service started {{ daemon_name }}
  tags:
    - skip-check
    - service_start
