---
- name: Install Server
  yum:
    name: mariadb-server

- name: Daemon Started
  include_role:
    name: common_tasks
    tasks_from: service_started_{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml

- include_role:
    name: common_tasks
    tasks_from: flush_handlers.yml
